project_id = "pifvubfmuubflsftgtrr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-invitation]
    verify_jwt = false
  [functions.send-sms]
    verify_jwt = false
